config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'messages#home'
  resources :messages do
    resources :comments
  end
  resources :employees
  resources :issues
  resources :comments
  get 'state/:id', to: 'issues#state'
  resources :admin_users,only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  has_one :user
  has_one :message
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :issues
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :employee
  enum level: {
    "低" => 0,
    "中" => 1,
    "高" => 2,
  }

  enum state: {
    "未修复" => 0,
    "已修复" => 1,
  }
end

app/models/message.rb
class Message < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  def index
    @users = User.all.order('created_at desc').page(params[:page]).per(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user! 
  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :username
      devise_parameter_sanitizer.for(:account_update) << :username
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @message = Message.find(params[:message_id])
    @comment = @message.comments.new(comments_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to message_path(@message)
  end

  def comments_params
    params.require(:comment).permit(:info, :infostatus, :message_id, :user_id)
  end
    
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.order("created_at desc").page(params[:page]).per(10)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_parames)
    if @employee.save
      redirect_to employees_path, notice: 'succeed'
    else
      redirect_to employees_path, notice: 'fail'
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    if @employee.destroy
      redirect_to action: :index
    else
      redirect_to action: :index
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_parames
      params.require(:employee).permit(:name)
    end
    
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def index
    @issues = Issue.order("created_at desc").page(params[:page]).per(10)
  end

  def new
    @issue = Issue.new
  end

  def create
    @issue = Issue.new(issue_parames)
    if @issue.save
      redirect_to issues_path, notice: 'succeed'
    else
      redirect_to issues_path, notice: 'fail'
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update(issue_parames)
      redirect_to issues_path, notice: 'succeed'
    else
      redirect_to issues_path, notice: 'fail'
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    if @issue.destroy
      redirect_to action: :index
    else
      redirect_to action: :index
    end
  end

  def state
    @issue = Issue.find(params[:id])
    if @issue.state == '未修复'
      @issue.update(state: 1)
      redirect_to issues_path, notice: 'succeed'
    else
      redirect_to issues_path, notice: 'It was fixed.'
    end
  end

  private
  
    def issue_parames
      params.require(:issue).permit(:level, :description, :state, :employee_id)
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  def home
    @messages = Message.order("created_at desc").page(params[:page]).per(10)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    @message.username = current_user.username
    if @message.save
      redirect_to root_url, notice: 'success.'
    else
      redirect_to root_url, notice: 'fail.'
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/admin_users/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="portlet box green">
        <div class="portlet-title">
          <div class="caption">用户列表</div>
          <div class="actions btn-group">
          </div>
        </div>
        <div class="portlet-body flip-scroll">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>邮箱</th>
                <th>账户</th>
                <th>最后操作时间</th>
                <th>操作</th>
              </tr>
            </thead>
            <tbody>
            <% @users.each do |n| %>
              <tr>
                <td><%= n.email %></td>
                <td><%= n.username %></td>
                <td><%= n.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
                <td><%= link_to '删除（并没有写）' %></td>
            <% end %>
            </tbody>
          </table>
          <%= paginate @users %>
        </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <div>
    <%= f.label :info %><br>
    <%= f.text_field :info, class: 'form-control', placeholder: 'Text', type: 'text' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/comments/index.html.erb
test

app/views/comments/new.html.erb
<%= render 'form' %>

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Text', type: 'text' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>

app/views/employees/index.html.erb
<h1>employees</h1>
<table class="table table-striped table-bordered table-responsive table-hover">
<thead>
  <tr>
    <th>name</th>
    <th>operate</th>
  </tr>
</thead>
<tbody>
<% @employees.each do |s| %>
  <tr>
    <td><%= s.name %></td>
    <td><%= link_to 'delete', employee_path(s), method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @employees %>
<%= link_to 'New', new_employee_path, class: 'btn btn-default' %>
<script type="text/javascript">$("#employee").addClass("active")</script>

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <div class="form-group">
    <%= f.label :level %>
    <%= f.select "level", Issue.levels.keys, {}, { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.select "state", Issue.states.keys, {}, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.label :employee_id %>
    <%= f.collection_select :employee_id, Employee.all, :id, :name, {}, { class: "form-control" } %>
  </div>


  <div class='form-group'>
    <%= f.label :description %>
    <div>
      <textarea id="message_description" name="issue[description]"><%= @issue.description %></textarea>
      <div class="form-control-focus"> </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>
<script type="text/javascript">
  $(".field_with_errors").parents(".form-md-line-input").addClass("has-error")
  $(".field_with_errors").append('<div class="form-control-focus"> </div>')
  var editor = new Simditor({
    textarea: $('#message_description'),
    toolbar: [
          'bold', 'italic', 'underline', '|', 
          'ol', 'ul', 'blockquote', 'code', '|', 
          'link', 'image', '|', 
          'indent', 'outdent', '|', 
          'hr', 'table'
          ],
    pasteImage: true
  });
  $("#message_description").hide()
</script>

app/views/issues/edit.html.erb
<%= render 'form' %>

app/views/issues/index.html.erb
<h1>issues</h1>
<table class="table table-striped table-bordered table-responsive table-hover">
<thead>
  <tr>
    <th>id</th>
    <th>level</th>
    <th>create time</th>
    <th>update time</th>
    <th>state</th>
    <th>employee</th>
    <th>description</th>
    <th>operate</th>
  </tr>
</thead>
<tbody>
<% @issues.each do |s| %>
  <tr>
    <td><%= s.id %></td>
    <td><%= s.level %></td>
    <td><%= s.created_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
    <td><%= s.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
    <td><%= s.state %></td>
    <td><%= s.employee.try(:name) %></td>
    <td><%= raw s.description[0..25] %></td>
    <td><%= link_to 'edit', edit_issue_path(s) %>
    <%= link_to 'delete', issue_path(s), method: :delete , data: { confirm: '是否确认！'} %>
    <a href="state/<%= s.id %>">state</a>
    </td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @issues %>
<%= link_to 'New', new_issue_path, class: 'btn btn-default' %>
<script type="text/javascript">$("#issues").addClass("active")</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'index', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 56px;">
<%= render 'shared/head' %>
  <div class="container">
    <div class="row">
    <% unless notice.nil? %>
    <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% unless alert.nil? %>
    <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
    </div>
  </div>
<a href="#" class="scrollToTop" style="display: none;">
  <div id="toTopRope"></div>
  <img id="toTopHover" src="/topscroll.png">
</a>
</body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'index', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'index', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 56px;">
<%= render 'shared/head' %>
  <div class="container">
    <div class="row">
    <% unless notice.nil? %>
    <div class="alert alert-info"><%= notice %></div>
    <% end %>
    <% unless alert.nil? %>
    <div class="alert alert-danger"><%= alert %></div>
    <% end %>
    <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title,class: 'form-control', placeholder: 'Text', type: 'text' %>
  </div>
  <div class='form-group'>
    <%= f.label :description %>
    <div>
      <textarea id="message_description" name="message[description]"><%= @message.description %></textarea>
      <div class="form-control-focus"> </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-default' %>
  </div>
<% end %>
<script type="text/javascript">
  $(".field_with_errors").parents(".form-md-line-input").addClass("has-error")
  $(".field_with_errors").append('<div class="form-control-focus"> </div>')
  var editor = new Simditor({
    textarea: $('#message_description'),
    toolbar: [
          'bold', 'italic', 'underline', '|', 
          'ol', 'ul', 'blockquote', 'code', '|', 
          'link', 'image', '|', 
          'indent', 'outdent', '|', 
          'hr', 'table'
          ],
    pasteImage: true
  });
  $("#message_description").hide()
</script>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>
<br>
<p>
<%= link_to 'Show', @message, class: 'btn btn-default' %> 
<%= link_to 'Back', messages_path, class: 'btn btn-default' %>
</p>

app/views/messages/home.html.erb
<div class="col-md-9">
  <% @messages.each do |message| %>
  <div class="topics panel panel-default">
    <div class="panel-body">
      <div class="topic media">
        <div class="infos media-body">
          <div class="title media-heading">
            <a href="<%= message_path(message) %>
              ">
              <%= message.title %></a>
          </div>
          <footer style="text-align: right;">
            <%= message.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          </footer>
          <footer style="text-align: right;">
           by — <%= message.username %>
          </footer>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div style="text-align: center;">
    <%= paginate @messages %></div>
</div>

<div class="sidebar col-md-3">

  <div class="panel panel-default">
    <div class="panel-heading">操作</div>
    <a href="<%= new_message_path %>" class="btn btn-success btn-block btn-focus-reply">发帖</a>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading">友情网站</div>
<!--     <ul class="list-group" style="text-align:center">
      <li class="list-group-item">
        <a href="https://www.upyun.com/" rel="nofollow" title="" target="_blank">
          <img src="/upyun.png" style="width:120px;margin: 4px 0;"></a>
      </li>
    </ul> -->
  </div>

  <!--     <div class="panel panel-default">
  <div class="panel-heading">统计信息</div>
  <ul class="list-group">
    <li class="list-group-item">社区会员:  人</li>
    <li class="list-group-item">帖子数:  个</li>
    <li class="list-group-item">回帖数:  条</li>
  </ul>
</div>
-->
</div>
<script type="text/javascript">$("#homepage").addClass("active")</script>

app/views/messages/index.html.erb
<div class="col-md-9">
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>
  <tbody>
    <% @messages.each do |message| %>
        <div>title:<%= message.title %></div>
        <div>description:<%= raw message.description[0..200] %></div>
        <div>
        <%= link_to 'Show', message, class: 'btn btn-default' %>
        <%= link_to 'Edit', edit_message_path(message), class: 'btn btn-default' %>
        <%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </div>
    <% end %>
  </tbody>
<%= link_to 'New Message', new_message_path, class: 'btn btn-default' %>
</div>
<script type="text/javascript">
  $("#backend").addClass("active")
</script>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path, class: 'btn btn-default' %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @message.title %>
</p>

<p>
  <strong>Description:</strong>
  <textarea id="message_description" name="message[description]"><%= @message.description %></textarea>
</p>

<%= link_to 'Edit', edit_message_path(@message), class: 'btn btn-default' %> 
<%= link_to 'Back', messages_path, class: 'btn btn-default' %>

<h2>Comments</h2>
<% @message.comments.each do |comment| %>
  <div class="topics panel panel-default">
    <div class="panel-body">
      <div class="topic media">
        <div class="infos media-body">
          <div class="title media-heading">
              <%= comment.info %>
          </div>
          <footer style="text-align: right;">
            <% @id = comment.user_id %>
            by--<%= User.find(@id).username %>
          </footer>
        </div>
      </div>
    </div>
  </div>
<% end %>
<h2>Add a comment:</h2>
<%= form_for([@message, @message.comments.build]) do |f| %>
  <p>
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<script type="text/javascript">
  $(".field_with_errors").parents(".form-md-line-input").addClass("has-error")
  $(".field_with_errors").append('<div class="form-control-focus"> </div>')
  var editor = new Simditor({
    textarea: $('#message_description'),
    toolbar: [
          'bold', 'italic', 'underline', '|', 
          'ol', 'ul', 'blockquote', 'code', '|', 
          'link', 'image', '|', 
          'indent', 'outdent', '|', 
          'hr', 'table'
          ],
    pasteImage: true
  });
  $("#message_description").hide()
</script>

<script type="text/javascript">
  $(".field_with_errors").parents(".form-md-line-input").addClass("has-error")
  $(".field_with_errors").append('<div class="form-control-focus"> </div>')
  var editor = new Simditor({
    textarea: $('#comment_info'),
    toolbar: [
          'bold', 'italic', 'underline', '|', 
          'ol', 'ul', 'blockquote', 'code', '|', 
          'link', 'image', '|', 
          'indent', 'outdent', '|', 
          'hr', 'table'
          ],
    pasteImage: true
  });
  $("#comment_info").hide()
</script>

app/views/shared/_head.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container">
   <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">LiFESICK</a>
   </div>
   <div>
      <ul class="nav navbar-nav">
         <li id="homepage">
            <a href="<%= root_path %>">首页</a>
         </li>
         <li id="backend">
            <a href="<%= messages_path %>">后台</a>
         </li>
         <li id="employee">
            <a href="<%= employees_path %>">employee</a>
         </li>
         <li id="issues">
            <a href="<%= issues_path %>">issue</a>
         </li>
<!--          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               Java <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li>
                  <a href="#">jmeter</a>
               </li>
               <li>
                  <a href="#">EJB</a>
               </li>
               <li>
                  <a href="#">Jasper Report</a>
               </li>
               <li class="divider"></li>
               <li>
                  <a href="#">分离的链接</a>
               </li>
               <li class="divider"></li>
               <li>
                  <a href="#">另一个分离的链接</a>
               </li>
            </ul>
         </li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
        <li><%= link_to('修改密码', edit_registration_path(:user)) %></li>
      <li><%= link_to(current_user.username) %></li>
      <% else %>
        <li><%= link_to('注册', new_registration_path(:user)) %></li>
        <li><%= link_to('登陆', new_session_path(:user)) %></li>
      <% end %>
      </ul>
   </div>
   </div>
</nav>